server:
  port: 9001

spring:
  application:
    name: spring-db202507
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update # 실제로 앱을 돌릴 때는 none으로 바꿔야 한다.
    properties:
      hibernate:
        format_sql: true
    database: mysql

# MyBatis Setting
mybatis:
  # SQL file location
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.database.chap03

logging:
  level:
    root: INFO
    com.spring.database: DEBUG
    org:
      hibernate:
        SQL: DEBUG